//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace SyncDirCmd {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SyncDirCmd.Config")]
    [System.Xml.Serialization.XmlRootAttribute("config", Namespace="SyncDirCmd.Config", IsNullable=false)]
    public partial class Config {
        
        private Sync[] syncField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sync")]
        public Sync[] sync {
            get {
                return this.syncField;
            }
            set {
                this.syncField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SyncDirCmd.Config")]
    public partial class Sync {
        
        private string nameField;
        
        private string leftField;
        
        private string rightField;
        
        private Master masterField;
        
        private bool masterFieldSpecified;
        
        private string[] ignoreField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
            }
        }
        
        /// <remarks/>
        public string right {
            get {
                return this.rightField;
            }
            set {
                this.rightField = value;
            }
        }
        
        /// <remarks/>
        public Master master {
            get {
                return this.masterField;
            }
            set {
                this.masterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool masterSpecified {
            get {
                return this.masterFieldSpecified;
            }
            set {
                this.masterFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ignore")]
        public string[] ignore {
            get {
                return this.ignoreField;
            }
            set {
                this.ignoreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SyncDirCmd.Config")]
    public enum Master {
        
        /// <remarks/>
        left,
        
        /// <remarks/>
        right,
        
        /// <remarks/>
        both,
    }
}
